### ISSUE TITLE
Support weird syntax

### ISSUE THREAD

**Issue by aske02** [Vurv78/LuaPro#21] opened 2023-08-04 07:29 UTC
I have encountered problems using this, as people seem to have many weird ways of doing their code, and Lua seems to support it all. But it breaks the parser / formatter.

```lua
GetTable('A').Tab = 200
-- Error when running: ../src/lib/mod.lua:15: Failed to parse: 'Token { variant: 1, data: GetTable }'
```
```lua
local A = { B = 'lower' }
string[A.B] 'AA_BB'
-- Error when running: ../src/lib/mod.lua:15: Failed to parse: 'Token { variant: 1, data: string }'
```
```lua
local B = { P = print }
B['P'] { A = 200 }
-- Error when running: ../src/lib/mod.lua:15: Failed to parse: 'Token { variant: 1, data: B }'
```
```lua
local Tab = {}
function GetTable()
	return Tab
end

GetTable {}[1] = 200

print(Tab[1]) -- prints 200

-- Error when running: ../src/lib/mod.lua:15: Failed to parse: 'Token { variant: 1, data: GetTable }'
```

I am aware that a lot of these are the result of some bad code, this is more for support of this actually valid syntax.

**Comment by Vurv78** [comment] 2023-08-04 18:05
2 and 3 are probably due to me thinking that the string/table syntax sugar only worked with identifiers.

1 and 4 are duplicate of https://github.com/Vurv78/LuaPro/issues/19

**Closed** 2023-08-04 18:15 UTC
